export const foods = [
  {
    name: "Кимчи жигэ",
    ingredients: [
      " Үхрийн мах",
      "Төмс",
      "Сармис",
      "Улаан,Ногоон чинжүү",
      "Сонгино",
      "Байцаа",
      "Лууван",
      "Хайрсан гурил",
      "Сүүл",
    ],
    portion: "1Таваг",
    price: "5000",
    count: 0,
    img: "https://media.istockphoto.com/photos/korean-cuisine-picture-id636460624?k=20&m=636460624&s=612x612&w=0&h=yLbR9FE4FMnHXGqTqHIZgpK5wuA9khpJH0eI88lWeYM=",
  },
  {
    name: "Кимбаб",
    ingredients: [" Үхрийн мах", "Гурил", "Сармис", "Сонгино", "Сүүл", "Гоньд"],
    portion: "1ширхэг",
    price: "5000",
    count: 0,
    img: "https://c0.wallpaperflare.com/preview/865/442/492/korean-food-koreanm-kimbap-korean-breakfast.jpg",
  },
  {
    name: "Шорлог",
    ingredients: [" Үхрийн мах", "Гурил", "Сармис", "Сонгино", "Сүүл", "Гоньд"],
    price: "5000",
    count: 0,
    img: "https://thumbs.dreamstime.com/b/chicken-kebab-bamboo-skewers-chicken-kebab-bamboo-skewers-frying-pan-114812842.jpg",
  },
  {
    name: "Төмсний хучмал",
    ingredients: [
      " Үхрийн мах",
      "Гурил",
      "Сармис",
      "Сонгино",
      "Сүүл",
      "Гоньд",
      "Төмс",
      "Будаа",
    ],
    price: "5000",
    count: 0,
    img: "https://senbii.com/wp-content/uploads/2019/02/00-82.jpg",
  },
];